document.getElementById('generate-button').addEventListener('click', generateScandal);

function generateScandal() {
    const people = [
        "prezes klubu", "działacz", "piłkarz", "baron", "bramkarz", "kapitan", "trener", 
        "lekarz sportowy", "sędzia piłkarski", "kolega prezesa", "kibic", "menadżer drużyny", 
        "asystent trenera", "psycholog sportowy", "rzecznik prasowy", "dyrektor sportowy", 
        "fizjoterapeuta", "scout", "agent piłkarski", "zawodnik rezerwowy", "legendarny piłkarz", 
        "właściciel klubu", "sponsor drużyny", "trener bramkarzy", "trener przygotowania fizycznego", 
        "analityk taktyczny", "dietetyk sportowy", "kucharz drużyny", "kierownik drużyny", 
        "członek zarządu", "wolontariusz klubowy", "koordynator ds. młodzieży", "były zawodnik", 
        "dyrektor akademii piłkarskiej", "komentator sportowy", "dziennikarz sportowy", 
        "technik sprzętowy", "osobisty trener piłkarza", "fanatyk klubowy", "młody talent"
    ];
    const actions = [
        "ustawiał mecze", "brał łapówki", "był pod wpływem alkoholu przed meczem", 
        "fałszował dokumenty", "został uderzony tacką na dokumenty", 
        "kupił mecz dla swojej drużyny", "pobił się z kibicem", "manipulował wynikami zakładów bukmacherskich", 
        "fałszował dokumenty finansowe", "był zamieszany w korupcję", "manipulował wynikami meczów", 
        "znęcał się nad zawodnikami", "sprzedał klub podejrzanym inwestorom", "stosował doping", 
        "używał obraźliwego języka wobec zawodników", "obstawiał wyniki meczów", "przepił cały budzet klubu", "wysłał mlodego po szlugi"
    ];
    const reasons = [
        "w celu zdobycia przewagi w lidze", 
        "dla szybszego powrotu do zdrowia", 
        "pod presją ze strony zarządu", 
        "pod wpływem stresu", 
        "dla korzyści finansowych", 
        "pod wpływem impulsu", 
        "bo tak", 
        "z powodu złego dnia", 
        "po przegranej grze w karty", 
        "z powodu przegranej zakładu", 
        "bo nie lubi swojego szefa", 
        "bo był w złym humorze", 
        "bo stracił ulubioną koszulkę", 
        "bo mu się nudziło", 
        "bo chciał udowodnić coś koledze", 
        "po kłótni z partnerką", 
        "bo źle zrozumiał instrukcje", 
        "bo pomylił mecz z treningiem", 
        "bo zaspał i się spóźnił", 
        "bo miał pecha przez cały dzień", 
        "bo zgubił klucze do szatni", 
        "bo miał zły sen o meczu", 
        "bo przegrał zakład z kolegą", 
        "bo pomylił dzień tygodnia", 
        "bo zapomniał o urodzinach trenera", 
        "bo chciał zaimponować fanom", 
        "bo chciał zostać bohaterem memów", 
        "bo wypił za dużo alkoholu", 
        "bo pomylił datę meczu", 
        "bo nie zgodził się z decyzją sędziego", 
        "bo miał konflikt z trenerem", 
        "bo klub nie wypłacił mu pensji na czas", 
        "bo nie dostał awansu w klubie", 
        "bo miał problemy z kontraktem", 
        "bo chciał opuścić klub", 
        "bo chciał wynegocjować lepszy kontrakt", 
        "bo przyszedł na trening po imprezie", 
        "bo pił alkohol w trakcie meczu", 
        "bo nie pojawił się na ważnym spotkaniu", 
        "bo miał problemy z zarządem klubu", 
        "bo nie zgodził się z taktyką trenera", 
        "bo chciał zostać transferowany", 
        "bo miał konflikt z właścicielem klubu", 
        "bo źle zarządzał funduszami klubu", 
        "bo uczestniczył w nielegalnych zakładach", 
        "bo miał romans z osobą z klubu", 
        "bo nie przestrzegał regulaminu klubu", 
        "bo nie pojawił się na meczu", 
        "bo krytykował klub w mediach", 
        "bo zorganizował nielegalną imprezę w klubie", 
        "bo naruszył zasady fair play", 
        "bo nie przestrzegał diety sportowej",
        "bo próbował oszukać na treningu", 
        "bo zignorował zalecenia lekarza", 
        "bo pokłócił się z fanami", 
        "bo zablokował transfer innego zawodnika", 
        "bo wziął udział w bójce na boisku", 
        "bo nie stawił się na konferencji prasowej", 
        "bo za dużo imprezował", 
        "bo wynosił informacje z szatni",
        "bo zapomniał taktyki meczowej", 
        "bo nie przygotował zespołu na mecz", 
        "bo nie wykonał poleceń trenera", 
        "bo krytykował taktykę w mediach", 
        "bo nie przestrzegał godzin ciszy nocnej", 
        "bo ignorował zalecenia dietetyka", 
        "bo nie pojawił się na spotkaniu zarządu", 
        "bo nie zgodził się na redukcję pensji", 
        "bo publicznie skrytykował klub", 
        "bo naruszył przepisy dotyczące transferów", 
        "bo popadł w konflikt z innym zawodnikiem", 
        "bo nie przestrzegał zasad bezpieczeństwa", 
        "bo zorganizował nielegalne zakłady w klubie", 
        "bo nie pojawił się na badaniach antydopingowych", 
        "bo nie zastosował się do strategii zespołu", 
        "bo dlaczego nie", 
        "bo spóźnił się na trening", 
        "bo nie przestrzegał zaleceń fizjoterapeuty", 
        "bo zignorował zalecenia trenera bramkarzy", 
        "bo nie pojawił się na meczu rezerw", 
        "bo zorganizował nielegalne spotkanie drużyny", 
        "bo nie przestrzegał zasad higieny"
    ];
    const person = people[Math.floor(Math.random() * people.length)];
    const action = actions[Math.floor(Math.random() * actions.length)];
    const reason = reasons[Math.floor(Math.random() * reasons.length)];

    const output = `W polskiej piłce ${person} ${action} ${reason}.`;
    document.getElementById('output').innerText = output;
}
